[package]
name = "wapr"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["dylib", "rlib"]
path = "src/lib.rs"

[dependencies]


[dev-dependencies]
rand = "0.8.4"
criterion = "0.3.4"

[[bench]]
name = "art_bench"
path = "benches/art_bench.rs"
harness = false